FusionCharts.ready(function () {
   var revenueChart = new FusionCharts({
       type: 'mscombidy2d',
       renderAt: 'chart-container',
       width: '650',
       height: '500',
       dataFormat: 'json',
       dataSource: {
           "chart": {
               "showYAxisValues": "1",
                   "showlegend": "0",
                   "labeldisplay": "ROTATE",
                   "chartTopMargin": "50",
                   "chartLeftMargin": "50",
               //Cosmetics
               "paletteColors": "#0075c2,#1aaf5d,#f2c500",
                   "baseFontColor": "#333333",
                   "baseFont": "Helvetica Neue,Arial",
                   "showLimits": "0",
                   "showBorder": "0",
                   "bgColor": "#DDDDDD",
                   "bgAlpha": "50",
                   "showShadow": "0",
                   "canvasBgColor": "#ffffff",
                   "canvasbrAlpha": "50",
                   "numdivlines": "0",
               // "usePlotGradientColor": "0",
 
               "showXAxisLine": "1",
                   "showVLineLabelBorder": "0"
 
           },
               "categories": [{
               "category": [{
                   "vline": "true",
                       "lineposition": "0"
               }, {
                   "label": "awful"
               }, {
                   "vline": "true",
                       "lineposition": "0"
               }, {
                   "label": "coarse"
               }, {
                   "vline": "true",
                       "lineposition": "0"
               }, {
                   "label": "helish"
               }, {
                   "vline": "true",
                       "lineposition": "0"
               }, {
                   "label": "rough"
               }, {
                   "vline": "true",
                       "lineposition": "0"
               }, {
                   "label": "harsh"
               }, {
                   "vline": "true",
                       "lineposition": "0"
               }, {
                   "label": "dirty"
               }, {
                   "vline": "true",
                       "lineposition": "0"
               }, {
                   "label": "little"
               }, {
                   "vline": "true",
                       "lineposition": "0"
               }, {
                   "label": "powerless"
               }, {
                   "vline": "true",
                       "lineposition": "0"
               }, {
                   "label": "weak"
               }, {
                   "vline": "true",
                       "lineposition": "0"
               }, {
                   "label": "short"
               }, {
                   "vline": "true",
                       "lineposition": "0"
               }, {
                   "label": "empty"
               }, {
                   "vline": "true",
                       "lineposition": "0"
               }, {
                   "label": "few"
               }, {
                   "vline": "true",
                       "lineposition": "0"
               }, {
                   "label": "freezing"
               }, {
                   "vline": "true",
                       "lineposition": "0"
               }, {
                   "label": "cold"
               }, {
                   "vline": "true",
                       "lineposition": "0"
               }, {
                   "label": "slow"
               }, {
                   "vline": "true",
                       "lineposition": "0"
               }, {
                   "label": "dull"
               }, {
                   "vline": "true",
                       "lineposition": "0"
               }, {
                   "label": "dark"
               }, {
                   "vline": "true",
                       "lineposition": "0"
               }, {
                   "label": "old"
               }, {
                   "vline": "true",
                       "lineposition": "0"
               }]
           }],
               "dataset": [{
               "seriesName": "Synonyms",
                   "renderAs": "line",
                   "showValues": "0",
                   "anchorSides": "3",
                   "data": [{
                   "value": "5"
               }, {
                   "value": "2"
               }, {
                   "value": "4"
               }, {
                   "value": "5"
               }, {
                   "value": "3"
               }, {
                   "value": "7"
               }, {
                   "value": "8"
               }, {
                   "value": "7"
               }, {
                   "value": "5"
               }, {
                   "value": "6"
               }, {
                   "value": "2"
               }, {
                   "value": "2"
               }, {
                   "value": "6"
               }, {
                   "value": "5"
               }, {
                   "value": "6"
               }, {
                   "value": "6"
               }, {
                   "value": "5"
               }, {
                   "value": "2"
               }]
           }, {
               "seriesName": "Antonyms",
                   "parentYAxis": "S",
                   "renderAs": "line",
                   "showValues": "0",
                   "anchorSides": "4",
                   "dashed": "1",
                   "data": [{
                   "value": "1"
               }, {
                   "value": "2"
               }, {
                   "value": "3"
               }, {
                   "value": "4"
               }, {
                   "value": "7"
               }, {
                   "value": "9"
               }, {
                   "value": "1"
               }, {
                   "value": "6"
               }, {
                   "value": "7"
               }, {
                   "value": "2"
               }, {
                   "value": "9"
               }, {
                   "value": "1"
               }, {
                   "value": "4"
               }, {
                   "value": "7"
               }, {
                   "value": "2"
               }, {
                   "value": "9"
               }, {
                   "value": "3"
               }, {
                   "value": "2"
               }]
           }],
               "annotations": {
               "groups": [{
                   "color": "#000000",
                       "rotateText": "1",
                       
                       "items": [{
                       "type": "text",
                           "text": "nice**",
                           "x": "$chartTopMargin+5",
                           "y": "$chartTopMargin-20",
                   }, {
                       "type": "text",
                           "text": "fine",
                           "x": "$chartTopMargin+25",
                           "y": "$chartTopMargin-20",
                   }, {
                       "type": "text",
                           "text": "heavenly",
                           "x": "$chartTopMargin+50",
                           "y": "$chartTopMargin-20",
                   }, {
                       "type": "text",
                           "text": "smooth",
                           "x": "$chartTopMargin+70",
                           "y": "$chartTopMargin-20",
                   }, {
                       "type": "text",
                           "text": "mild",
                           "x": "$chartTopMargin+92",
                           "y": "$chartTopMargin-20",
                   }, {
                       "type": "text",
                           "text": "clean",
                           "x": "$chartTopMargin+115",
                           "y": "$chartTopMargin-20",
                   }, {
                       "type": "text",
                           "text": "big",
                           "x": "$chartTopMargin+138",
                           "y": "$chartTopMargin-20",
                   }, {
                       "type": "text",
                           "text": "powerful",
                           "x": "$chartTopMargin+160",
                           "y": "$chartTopMargin-20",
                   }, {
                       "type": "text",
                           "text": "strong",
                           "x": "$chartTopMargin+180",
                           "y": "$chartTopMargin-20",
                   }, {
                       "type": "text",
                           "text": "long",
                           "x": "$chartTopMargin+200",
                           "y": "$chartTopMargin-20",
                   }, {
                       "type": "text",
                           "text": "full",
                           "x": "$chartTopMargin+225",
                           "y": "$chartTopMargin-20",
                   }, {
                       "type": "text",
                           "text": "many",
                           "x": "$chartTopMargin+245",
                           "y": "$chartTopMargin-20",
                   }, {
                       "type": "text",
                           "text": "burning",
                           "x": "$chartTopMargin+265",
                           "y": "$chartTopMargin-20",
                   }, {
                       "type": "text",
                           "text": "hot",
                           "x": "$chartTopMargin+290",
                           "y": "$chartTopMargin-20",
                   }, {
                       "type": "text",
                           "text": "fast",
                           "x": "$chartTopMargin+310",
                           "y": "$chartTopMargin-20",
                   }, {
                       "type": "text",
                           "text": "sharp",
                           "x": "$chartTopMargin+335",
                           "y": "$chartTopMargin-20",
                   }, {
                       "type": "text",
                           "text": "light",
                           "x": "$chartTopMargin+355",
                           "y": "$chartTopMargin-20",
                   }, {
                       "type": "text",
                           "text": "young",
                           "x": "$chartTopMargin+375",
                           "y": "$chartTopMargin-20",
                   }, {
                       "type": "text",
                           "text": "FusionCharts Sample",
                           "x": "$chartRightMargin",
                           "y": "$chartRightMargin+120",
                           "fontSize": "20",
                           "bold": "1"
                   }
 
 
 
                   ]
               }]
           }
       }
   });
 
   revenueChart.render();
 });